// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace application.Models;

public partial class Course
{
    public int CourseID { get; set; }

    public string CourseName { get; set; }

    public int DeptID { get; set; }

    public int InstructorID { get; set; }

    public virtual ICollection<CourseTopic> CourseTopics { get; set; } = new List<CourseTopic>();

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual Instructor Instructor { get; set; }

    public virtual ICollection<QuestionPool> QuestionPools { get; set; } = new List<QuestionPool>();

    public virtual ICollection<StudentGrade> StudentGrades { get; set; } = new List<StudentGrade>();
}