// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace application.Models
{
    public partial class getAllStudentExamQuestionsResult
    {
        public int SelectedAnswerIndex { get; set; }
        public int ExamID { get; set; }
        public int QuestionID { get; set; }
        public int StudentID { get; set; }
    }
}
