// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace application.Models
{
    public partial class getAllQuestionPoolsResult
    {
        public int QuestionID { get; set; }
        public string Title { get; set; }
        public int QuestionType { get; set; }
        public int CorrectAnswerIndex { get; set; }
        public int Grade { get; set; }
        public int CourseID { get; set; }
    }
}
