// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace application.Models
{
    public partial class getallinstructorsResult
    {
        public int BranchID { get; set; }
        public int InstructorID { get; set; }
    }
}
