// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace application.Models
{
    public partial class GetAllQuestionsResult
    {
        public int QuestionID { get; set; }
        public bool? isSelected { get; set; }
        public string Title { get; set; }
        public int CorrectAnswerIndex { get; set; }
        public int Grade { get; set; }
        public string Choice { get; set; }
    }
}
