// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace application.Models
{
    public partial class getBranchesDepartmentsResult
    {
        public int DeptID { get; set; }
        public string DeptName { get; set; }
        public int? BranchId { get; set; }
    }
}
