// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace application.Models
{
    public partial class GetCoursesByInstructorIDResult
    {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
    }
}
