// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace application.Models
{
    public partial class GetExamsDeptCourseResult
    {
        public int ExamID { get; set; }
        public DateTime ExamDate { get; set; }
        public int Duration { get; set; }
    }
}
