// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace application.Models
{
    public partial class GetStudentExamDetailsResult
    {
        [Column("Question Title")]
        public string QuestionTitle { get; set; }
        public int SelectedAnswerIndex { get; set; }
        public int CorrectAnswerIndex { get; set; }
        [Column("Question Grade")]
        public int QuestionGrade { get; set; }
    }
}
