// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace application.Models
{
    public partial class GetStudentGradesResult
    {
        [Column("Student Grade")]
        public int? StudentGrade { get; set; }
        [Column("Total Grade")]
        public int? TotalGrade { get; set; }
    }
}
