// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace application.Models;

public partial class Instructor_Course
{
    public int CourseID { get; set; }

    public int InstructorID { get; set; }

    public virtual Course Course { get; set; }

    public virtual Instructor Instructor { get; set; }
}