// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace application.Models;

public partial class Instructor
{
    public int BranchID { get; set; }

    public int InstructorID { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual User InstructorNavigation { get; set; }

    public virtual ICollection<Instructor_Course> Instructor_Courses { get; set; } = new List<Instructor_Course>();
}