// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace application.Models;

public partial class Instructor
{
    public int? DeptID { get; set; }

    public int InstructorID { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual Department Dept { get; set; }

    public virtual User InstructorNavigation { get; set; }
}