// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace application.Models;

public partial class QuestionChoice
{
    public string Choice { get; set; }

    public int QuestionID { get; set; }

    public int ChoiceIndex { get; set; }

    public virtual QuestionPool Question { get; set; }
}