// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace application.Models;

public partial class StudentExamQuestion
{
    public int SelectedAnswerIndex { get; set; }

    public int ExamID { get; set; }

    public int QuestionID { get; set; }

    public int StudentID { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual QuestionPool Question { get; set; }

    public virtual Student Student { get; set; }
}